services:
  - type: web
    name: todolist-app
    plan: free
    branch: main
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.java
